name: Build and deploy a Node.js app and an Angular app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Change working directory to the Angular app
        run: cd apps/share-a-meal-web

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifacts for deployment
        run: |
          echo ${GITHUB_WORKSPACE}
          zip -r ${GITHUB_WORKSPACE}/share-a-meal-web-release.zip .

      - name: Upload frontend-app artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: share-a-meal-web
          path: share-a-meal-web-release.zip

  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: share-a-meal-web

      - name: Unzip artifact for deployment
        run: unzip share-a-meal-web-release.zip

      - name: Deploy to static Azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./src"
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional

  deploy-data-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ needs.deploy-frontend-app.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: data-api-release   # Update this line to match the correct artifact name
          path: ${{ github.workspace }}  # Specify the target path for the downloaded artifact

      - name: Unzip artifact for deployment
        run: unzip ${{ github.workspace }}/data-api-release.zip

      - name: Install dependencies
        run: npm install

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NxWorkshop'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: .
