# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy a Node.js app and an Angular app to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifacts for deployment
        run: |
          cd ${GITHUB_WORKSPACE}/apps/data-api/ && zip -r ${GITHUB_WORKSPACE}/data-api-release.zip ./*
          cd ${GITHUB_WORKSPACE}/apps/share-a-meal-web/ && zip -r ${GITHUB_WORKSPACE}/share-a-meal-web-release.zip ./*

      - name: Upload frontend-app artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: share-a-meal-web
          path: share-a-meal-web-release.zip
          
      - name: Upload data-api artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: data-api-release
          path: data-api-release.zip

  deploy-frontend-app:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: share-a-meal-web

      - name: Unzip artifact for deployment
        run: unzip share-a-meal-web-release.zip

      - name: Deploy to static Azure web app
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.ANGULAR_PUBLISHTOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./src"
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional

          
  deploy-data-api:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ needs.deploy-frontend-app.outputs.webapp-url }}
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: data-api-release
          path: ${{ github.workspace }}/data-api-release
  
      - name: Change to the data-api directory
        run: cd ${{ github.workspace }}/data-api-release/apps/data-api
  
      - name: Install dependencies
        run: npm install
  
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'NxWorkshop'
          slot-name: 'Production'
          publish-profile: ${{ secrets.NEXTJS_PUBLISHPROFILE }}
          package: .
